#!/usr/bin/env sh

set -eo pipefail

DOCKER_COMPOSE_VERSION=1.23.1
COMPOSE_PROJECT_NAME=wpheadless
COMPOSE_SERVICES_TYPE=${COMPOSE_SERVICES_TYPE:-services}

cd "$(dirname "$0")"

# extract DOCKER_ENV from .env if not passed directly
if [ -z "$DOCKER_ENV" -a -f .env ]; then
  DOCKER_ENV=$(source .env && echo $DOCKER_ENV)
fi

# docker run options

if [ -t 1 ]; then
  DOCKER_RUN_OPTIONS='-t'
fi

if [ -t 0 ]; then
  DOCKER_RUN_OPTIONS="${DOCKER_RUN_OPTIONS} -i"
fi

# docker-compose options

DOCKER_COMPOSE_OPTIONS='-f compose.d/common.yml'

if [ -f "compose.d/${COMPOSE_SERVICES_TYPE}.yml" ]; then
  DOCKER_COMPOSE_OPTIONS="${DOCKER_COMPOSE_OPTIONS} -f compose.d/${COMPOSE_SERVICES_TYPE}.yml"
fi

if [ -f "compose.d/${COMPOSE_SERVICES_TYPE}-${DOCKER_ENV}.yml" ]; then
  DOCKER_COMPOSE_OPTIONS="${DOCKER_COMPOSE_OPTIONS} -f compose.d/${COMPOSE_SERVICES_TYPE}-${DOCKER_ENV}.yml"
fi

# container running docker-compose will receive limited set of explicitly set environment variables
# docker-compose will use .env to set environment variables available for containers
docker \
  run --rm \
  $DOCKER_RUN_OPTIONS \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "${PWD}:${PWD}" \
  --workdir="$PWD" \
  --env DOMAIN \
  --env PWD \
  --env COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
  "docker/compose:${DOCKER_COMPOSE_VERSION}" \
  $DOCKER_COMPOSE_OPTIONS \
  "$@" \
  ;
