#!/usr/bin/env sh

set -eo pipefail

cd "$(dirname "$0")"
STAGE=$(cat .stage 2>/dev/null)
STAGE=${STAGE:-production}
DOCKER_COMPOSE_VERSION=1.23.1
COMPOSE_PROJECT_NAME=wp-headless

if [ -t 1 ]; then
  DOCKER_RUN_OPTIONS="-t"
fi

if [ -t 0 ]; then
  DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -i"
fi

docker \
  run --rm \
  $DOCKER_RUN_OPTIONS \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "${PWD}:${PWD}" \
  --workdir="${PWD}" \
  --env PWD="$PWD" \
  --env COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
  "docker/compose:${DOCKER_COMPOSE_VERSION}" \
  -f docker-compose.d/common.yml \
  -f "docker-compose.d/${STAGE}.yml" \
  "$@";
