#!/usr/bin/env sh

set -eo pipefail

cd "$(dirname "$0")"
TASKS_DIR="tasks"

if [ $# -eq 0 ]; then
  echo "Usage: $(basename "$0") <TASK> [ARGS...]"
  echo "Available tasks:"
  echo "  <task-service-name>-sh"
  echo "$(ls "$TASKS_DIR")" | sed 's/^/  /'
  exit 1
fi

TASK=$1
TASK_SERVICE=false

if grep -qe "^\S*task-${TASK}:$" compose.d/tasks.yml; then
  TASK_SERVICE="task-${TASK}"
elif grep -qe "^\s*task-${TASK%%-*}:$" compose.d/tasks.yml; then
  TASK_SERVICE="task-${TASK%%-*}"
fi

shift 1

TASK_FILE="${TASKS_DIR}/${TASK}"

if  [ "$TASK_SERVICE" != "false" ]; then
  if [ "${TASK#*-}" == "sh" ]; then
    if [ $# -eq 0 ]; then
      TASK="sh"
    else
      TASK="sh -c $@"
    fi
  elif [ -f "$TASK_FILE" ]; then
    TASK="$TASK_FILE"
  else
    echo "Task not found: '${TASK_FILE}'"
    exit 1
  fi

  COMPOSE_SERVICES_TYPE=tasks ./docker-compose \
    run --rm --service-ports "$TASK_SERVICE" $TASK "$@"
else
  if [ ! -f "$TASK_FILE" ]; then
    echo Task "$TASK" does not exist
    exit 1
  fi

  source "$TASK_FILE"
fi
