#!/usr/bin/env sh

set -eo pipefail

cd "$(dirname "$0")"
TASKS_DIR="tasks"

if [ $# -eq 0 ]; then
  echo "Usage: $(basename "$0") <TASK> [ARGS...]"
  echo "Available tasks:"
  echo "  <task-service-name>-sh"
  echo "$(ls "$TASKS_DIR")" | sed 's/^/  /'
  exit 1
fi

TASK=$1
TASK_SERVICE="task-${TASK%%-*}"
shift 1

if [ "${TASK#*-}" == "sh" ]; then
  if [ $# -eq 0 ]; then
    TASK="sh"
  else
    TASK="$@"
  fi
else
  TASK_FILE="${TASKS_DIR}/${TASK}"
  TASK="${TASK_FILE} $@"

  if [ ! -f "$TASK_FILE" ]; then
    echo Task "$TASK" does not exist
    exit 1
  fi
fi

if grep -m 1 -x -q -E "\s+${TASK_SERVICE}:" docker-compose.d/tasks.yml; then
  COMPOSE_SERVICES_TYPE=tasks ./docker-compose \
    run --rm --service-ports "$TASK_SERVICE" $TASK
else
  source "$TASK_FILE"
fi
