#!/usr/bin/env bash

set -eo pipefail
source tasks/.args

if [ -f .env ]; then
  echo "Error: wpheadless seems to be already installed! aborting..."
  exit 1
fi

# DOMAIN will be passed to docker containers
export DOMAIN

# Create http vhost for served domain
mkdir -p "var/vhosts/${DOMAIN}"

./run-task configure "$@"

if [ "$LETSENCRYPT" = "true" ]; then
  ./run-task leissue-standalone || \
    ./run-task openssl-self-signed
else
  ./run-task openssl-self-signed
fi

./run-task openssl-dhparam
./docker-compose up -d

./run-task wp-install "$@"
