#!/usr/bin/env bash

set -eo pipefail

DOMAIN="localhost"
STAGE="development"

for i in "$@"; do
  case $i in
    --domain=*)
      DOMAIN="${i#*=}"
      ;;
    --admin-email=*)
      ADMIN_EMAIL="${i#*=}"
      ;;
    --admin-password=*)
      ADMIN_PASSWORD="${i#*=}"
      ;;
    --stage=*)
      STAGE="${i#*=}"
      ;;
    --uploads-bucket=*)
      UPLOADS_BUCKET="${i#*=}"
      ;;
  esac
done

if [ "$STAGE" = "production" ]; then
  touch .production
  export DOMAIN
else
  rm -f .production
fi

./run-task configure \
  --domain="$DOMAIN" \
  --admin-email="$ADMIN_EMAIL"

if [ "$STAGE" = "production" ]; then
  ./run-task leissue-standalone || \
    ./run-task openssl-self-signed
else
  ./run-task openssl-self-signed
fi

./run-task openssl-dhparam
./docker-compose up -d

./run-task wp-install \
  --admin-password="$ADMIN_PASSWORD" \
  --uploads-bucket="$UPLOADS_BUCKET"
