#!/usr/bin/env sh

set -e

CERTBOT_OPTIONS="certonly -n --agree-tos --standalone"

echo "[leissue-standalone]: Requesting Letsencrypt certificate"
certbot \
  $CERTBOT_OPTIONS \
  -m "$ADMIN_EMAIL" \
  -d "$DOMAIN"

certificate_dir="$(
  find /etc/letsencrypt/live -type d \
    -name "$DOMAIN" -or -name "${DOMAIN}-*" \
    | sort -r \
    | head -n1
)"

active_certificate_dir="/etc/letsencrypt/active/${DOMAIN}"
mkdir -p "$active_certificate_dir"
ln -sf "$certificate_dir"/* "${active_certificate_dir}/"
