#!/usr/bin/env sh

set -e

certbot \
  certonly \
  -n \
  --agree-tos \
  --standalone \
  -m "$ADMIN_EMAIL" \
  -d "$DOMAIN"

openssl \
  dhparam \
  -dsaparam \
  -out "/etc/letsencrypt/live/${DOMAIN}/dhparam.pem" 4096
