#!/usr/bin/env sh

set -e

CERTBOT_OPTIONS="certonly -n --agree-tos --standalone"

if [ "$STAGE" != "production" ]; then
  CERTBOT_OPTIONS="${CERTBOT_OPTIONS} --staging"
  echo "[leissue-standalone]: Requesting Letsencrypt test certificate"
else
  echo "[leissue-standalone]: Requesting Letsencrypt certificate"
fi

certbot \
  $CERTBOT_OPTIONS \
  -m "$ADMIN_EMAIL" \
  -d "$DOMAIN" \
  ;
