#!/usr/bin/env sh

set -e

CERTBOT_OPTIONS="certonly -n --agree-tos --standalone"

if [ "$STAGE" != "production" ]; then
  CERTBOT_OPTIONS="${CERTBOT_OPTIONS} --staging"
  echo "[leissue-standalone]: Requesting Letsencrypt test certificate"
else
  echo "[leissue-standalone]: Requesting Letsencrypt certificate"
fi

certbot \
  $CERTBOT_OPTIONS \
  -m "$ADMIN_EMAIL" \
  -d "$DOMAIN"

certificate_dir="$(
  find /etc/letsencrypt/live -type d \
    -name '${DOMAIN}' -or -name '${DOMAIN}-*' \
    | sort -r \
    | head -n1
)"

certificate_name="$(basename "$certificate_dir")"
active_certificate_dir="/etc/letsencrypt/active/${certificate_name}"
mkdir -p "$active_certificate_dir"
ln -sf "${certificate_dir}/*" "${active_certificate_dir}/."
