#!/usr/bin/env sh

set -e

# Since certbot exit with 0 not only when certificate was renewed successfully
# but also when certificate is not yet due for renewal the only reliable
# method for catching certificate renewals is deploy-hook.
#
# Solution implemented here uses deploy-hook script to create a file at
# specific location and exit with 0 if it exists, or 1 otherwise.

DEPLOY_HOOK_PATH=/tmp/certbot-deploy-hook
SUCCESS_FLAG_FILE=/tmp/certbot-renew-success

cat > "$DEPLOY_HOOK_PATH" << EOT
#!/usr/bin/env sh
touch "${SUCCESS_FLAG_FILE}"
EOT
chmod +x "$DEPLOY_HOOK_PATH"
rm -f "$SUCCESS_FLAG_FILE"

CERTBOT_OPTIONS="certonly -n --agree-tos"

echo "[leissue-or-issue]: Requesting Letsencrypt certificate"
certbot \
  $CERTBOT_OPTIONS \
  --webroot --webroot-path="/var/www/vhosts/${DOMAIN}" \
  --deploy-hook="$DEPLOY_HOOK_PATH" \
  -m "$ADMIN_EMAIL" \
  -d "$DOMAIN" \
  $@ \
  ;

# exit here if file does not exist
test -f "$SUCCESS_FLAG_FILE"

# Update actual certificate symlink
certificate_dir="$(
  find /etc/letsencrypt/live -type d \
    -name "$DOMAIN" -or -name "${DOMAIN}-*" \
    | sort -r \
    | head -n1
)"

active_certificate_dir="/etc/letsencrypt/active/${DOMAIN}"
mkdir -p "$active_certificate_dir"
ln -sf "$certificate_dir"/* "${active_certificate_dir}/"
