#!/usr/bin/env bash

set -eo pipefail
source tasks/.args

CERTDIR="var/letsencrypt/active/${DOMAIN}"

mkcert \
  -cert-file "${CERTDIR}/fullchain.pem" \
  -key-file "${CERTDIR}/privkey.pem" \
  "${DOMAIN}"
