#!/usr/bin/env sh

set -e

mkdir -p "/etc/letsencrypt/active/${DOMAIN}"

openssl \
  req -subj "/CN=${DOMAIN}" \
  -x509 -newkey rsa:4096 -nodes -days 365 \
  -keyout /etc/letsencrypt/active/${DOMAIN}/privkey.pem \
  -out /etc/letsencrypt/active/${DOMAIN}/fullchain.pem
