#!/usr/bin/env bash

set -eo pipefail
source tasks/.args

BACKUP_DIR="snapshots"

if [ -f .env ]; then
  echo "Error: wpheadless seems to be already installed! aborting..."
  exit 1
fi

BACKUP_FILE_NAME="$1"
BACKUP_FILE_PATH="${BACKUP_DIR}/${BACKUP_FILE_NAME}"
[ ! -f "$BACKUP_FILE_PATH" ] && echo "No snapshot file found: ${BACKUP_FILE_PATH}" && exit 1

# restore dot-env file from archive
tar -xzf "$BACKUP_FILE_PATH" dot-env

# start mysql service before before restoring database
./docker-compose up -d mysql

# restore snapshot
./run-task wp-snapshot-restore "${BACKUP_FILE_NAME}"

# start rest of the services
./docker-compose up -d
