#!/usr/bin/env bash

set -eo pipefail

DUMP_DIR="var/backup"
DUMP_FILE_NAME="db.sql.gz"

NEW_DUMP_FILE_NAME="db-$(date +%Y%m%d-%H%M%S).sql"
NEW_DUMP_FILE_PATH="/tmp/${NEW_DUMP_FILE_NAME}"

mysqldump \
  -h "$DB_HOST" \
  -u "$DB_USER" \
  $([ ! -z "$DB_PASSWORD" ] && echo -p"$DB_PASSWORD") \
  -B "$DB_NAME" \
  -r "$NEW_DUMP_FILE_PATH"

gzip "$NEW_DUMP_FILE_PATH"
NEW_DUMP_FILE_PATH="${NEW_DUMP_FILE_PATH}.gz"
NEW_DUMP_FILE_NAME="db-$(date +%Y%m%d-%H%M%S).sql.gz"

mkdir -p "$DUMP_DIR"
cd "$DUMP_DIR"
mv "$NEW_DUMP_FILE_PATH" "./${NEW_DUMP_FILE_NAME}"
ln -sf "./${NEW_DUMP_FILE_NAME}" "$DUMP_FILE_NAME"
cd - > /dev/null

echo "Dump created: ${DUMP_DIR}/${NEW_DUMP_FILE_NAME}"
