#!/usr/bin/env bash

set -eo pipefail

for i in "$@"; do
  case $i in
    --admin-password=*)
      ADMIN_PASSWORD="${i#*=}"
      ;;
    --uploads-bucket=*)
      UPLOADS_BUCKET="${i#*=}"
      ;;
  esac
done

WEBROOT=/var/www/wordpress/html
WP="wp --allow-root --path="${WEBROOT}""

#
# Download & extract wp files into web root
#

[ -d "$WEBROOT" ] || mkdir -p "$WEBROOT"
if [ -z "$(ls -A "$WEBROOT")" ]; then
  $WP core download --version="$WORDPRESS_VERSION" --skip-content
  mkdir -p "${WEBROOT}/wp-content/themes"
  mkdir -p "${WEBROOT}/wp-content/plugins"
fi

#
# Prepare wp-config.php file
#

WP_CONFIG_PATH=$(dirname "$WEBROOT")/wp-config.php
echo "Generating ${WP_CONFIG_PATH}"
php "${APPROOT}/wordpress/wp-config-tpl.php" > "$WP_CONFIG_PATH"

#
# Copy mu-plugins
#

echo "Copying mu-plugins"
cp -rf "${APPROOT}/wordpress/mu-plugins" "${WEBROOT}/wp-content/"

#
# Symlink uploads to dedicated RW docker volume mount
#

rm -rf /var/www/wordpress/html/wp-content/uploads
ln -sf /var/www/wordpress-uploads /var/www/wordpress/html/wp-content/uploads
chmod 777 /var/www/wordpress-uploads

#
# Symlink custom plugins and themes
#

if [ ! -z "$(ls -A /var/www/wordpress-plugins/)" ]; then
  ln -sf /var/www/wordpress-plugins/* "${WEBROOT}/wp-content/plugins/"
fi

if [ ! -z "$(ls -A /var/www/wordpress-themes/)" ]; then
  ln -sf /var/www/wordpress-themes/* "${WEBROOT}/wp-content/themes/"
fi

#
# Create db and user if necessary
#

while ! mysqladmin ping -h"$DB_HOST" --silent; do
  echo Waiting for "$DB_HOST"
  sleep 1
done

mysql -h "$DB_HOST" -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'%';
EOF

#
# Install multisite wp
#

if ! $WP core is-installed --network; then
  WP_CORE_OPTIONS=""

  if [ "$STAGE" != "production" ]; then
    WP_CORE_OPTIONS="${WP_CORE_OPTIONS} --skip-email"
  fi

  if [ ! -z "$ADMIN_PASSWORD" ]; then
    WP_CORE_OPTIONS="${WP_CORE_OPTIONS} --admin_password=${ADMIN_PASSWORD}"
  fi

  $WP core multisite-install \
    --url="https://${DOMAIN}" \
    --title="$WORDPRESS_TITLE" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-config \
    $WP_CORE_OPTIONS \
    ;
fi

#
# Install & activate plugins
#

WP_ENABLED_PLUGINS=$($WP plugin list --field=name --status=active-network)

# Install ACF Pro from GitHub
if ! echo "$WP_ENABLED_PLUGINS" | grep -xq "advanced-custom-fields-pro"; then
  PLUGIN_URL="https://github.com/wp-premium/advanced-custom-fields-pro/archive/${ACF_PRO_VERSION}.zip"
  $WP plugin install "$PLUGIN_URL" --activate-network
fi

# Install CUN from GitHub
if ! echo "$WP_ENABLED_PLUGINS" | grep -xq "content-update-notifier"; then
  PLUGIN_URL="https://github.com/WpHeadless/content-update-notifier/archive/master.zip"
  $WP plugin install "$PLUGIN_URL" --activate-network
fi

# Install plugins from wordpress.org
for plugin_file in $WORDPRESS_PLUGINS; do
  PLUGIN_NAME="$(echo "$plugin_file" | cut -d = -f 1)"
  PLUGIN_VERSION="$(echo "$plugin_file" | cut -d = -f 2)"

  echo "$WP_ENABLED_PLUGINS" | grep -xq "$PLUGIN_NAME" || \
    $WP plugin install "$PLUGIN_NAME" --version="$PLUGIN_VERSION" --activate-network
done

#
# Configure plugins
#

if [ ! -z "$UPLOADS_BUCKET" ] && [ "$STAGE" = "production" ]; then
  # TODO configure amazon-s3-and-cloudfront plugin
  # TODO configure disable-comments plugin
  echo -n
fi
