#!/usr/bin/env bash

set -eo pipefail

TMP_DIR=$(mktemp -d)

BACKUP_FILE_PATH="var/backup/${1-${DOMAIN}.tar.gz}"
[ ! -f "$BACKUP_FILE_PATH" ] && echo "No backup file found" && exit 1

tar -C "$TMP_DIR" -xzf "$BACKUP_FILE_PATH"

mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" < "${TMP_DIR}/dump.sql" \
  && echo "Database restored"

cp "${TMP_DIR}/wp-config.php" /var/www/wordpress/wp-config.php \
  && echo "wp-config.php file restored"

cp "${TMP_DIR}/dot-env" . \
  && echo "dot-env file restored"

rm -rf "${TMP_DIR}"
