#!/usr/bin/env bash

set -eo pipefail

BACKUP_DIR="snapshots"
BACKUP_FILE_NAME="${DOMAIN}-$(date +%Y%m%d-%H%M%S).tar.gz"
BACKUP_FILE_PATH="${BACKUP_DIR}/${BACKUP_FILE_NAME}"
TMP_DIR=$(mktemp -d)

# db dump
mysqldump \
  -h "$DB_HOST" \
  -u "$DB_USER" \
  $([ ! -z "$DB_PASSWORD" ] && echo -p"$DB_PASSWORD") \
  -B "$DB_NAME" \
  -r "${TMP_DIR}/dump.sql"

# dot-env config
cp dot-env "$TMP_DIR"

mkdir -p "$BACKUP_DIR"

echo "Creating snapshot: ${BACKUP_FILE_NAME}"
tar -czf "$BACKUP_FILE_PATH" \
  -C "$TMP_DIR" \
  dot-env \
  dump.sql \
  -C / \
  var/wordpress \
  var/www

cd "$BACKUP_DIR"
ln -sf "./${BACKUP_FILE_NAME}" "${DOMAIN}.tar.gz"
cd - > /dev/null

echo "Snapshot created: ${BACKUP_FILE_PATH}"
