#!/usr/bin/env bash

set -eo pipefail

SITEURL="https://${DOMAIN}/"
MYSQL_CMD="mysql -N -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD} ${DB_NAME}"

# Update url for master site
$MYSQL_CMD <<EOF
UPDATE wp_site SET domain="${DOMAIN}";
UPDATE wp_blogs SET domain="${DOMAIN}";
UPDATE wp_sitemeta SET meta_value="${SITEURL}" WHERE meta_key="siteurl";
UPDATE wp_options SET option_value="${SITEURL}" WHERE option_name in ("siteurl", "home");
EOF

# Update url for all sites in multisite
echo 'show tables like "wp_%_options";' \
  | $MYSQL_CMD \
  | xargs -I % \
    $MYSQL_CMD <<EOF
      UPDATE
        %
      SET
        option_value=CONCAT('${SITEURL}', SUBSTRING_INDEX(option_value, '/', -1))
      WHERE option_name in ('siteurl', 'home');
EOF
