#!/usr/bin/env bash

set -eo pipefail

UPTODATE=0

# Wordpress core
LATEST_WORDPRESS_VERSION="$(php -r 'print_r(json_decode(file_get_contents("https://api.wordpress.org/core/version-check/1.7/"))->offers[0]->version);')"
if [ "$LATEST_WORDPRESS_VERSION" != "$WORDPRESS_VERSION" ]; then
  echo "Wordpress core: ${WORDPRESS_VERSION} -> ${LATEST_WORDPRESS_VERSION}"
  UPTODATE=1
fi

# Advanced Custom Fields Pro
LATEST_ACF_PRO_VERSION="$(curl -Ss https://api.github.com/repos/wp-premium/advanced-custom-fields-pro/tags | php -r 'echo json_decode(file_get_contents("php://stdin"))[0]->name;')"
if [ "$LATEST_ACF_PRO_VERSION" != "$ACF_PRO_VERSION" ]; then
  echo "Plugin ACF PRO: ${ACF_PRO_VERSION} -> ${LATEST_ACF_PRO_VERSION}"
  UPTODATE=1
fi

# Wordpress plugins
for plugin_file in $WORDPRESS_PLUGINS; do
  PLUGIN_NAME="$(echo "$plugin_file" | cut -d = -f 1)"
  PLUGIN_VERSION="$(echo "$plugin_file" | cut -d = -f 2)"
  LATEST_PLUGIN_VERSION="$(php -r "echo json_decode(file_get_contents(\"https://api.wordpress.org/plugins/info/1.0/${PLUGIN_NAME}.json\"))->version;")"

  if [ "$LATEST_PLUGIN_VERSION" != "$PLUGIN_VERSION" ]; then
    echo "Plugin ${PLUGIN_NAME}: ${PLUGIN_VERSION} -> ${LATEST_PLUGIN_VERSION}"
    UPTODATE=1
  fi
done

if [ $UPTODATE -eq 0 ]; then
  echo "Everything is up to date!"
fi
