version: "3"
services:
  cron:
    image: $IMAGE_CRON
    restart: unless-stopped
    working_dir: $PWD
    command: cron/docker_cmd.sh
    networks:
      - backend
    volumes:
      - ..:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APPROOT=$PWD
      - LETSENCRYPT
      - DOMAIN
  smtp:
    image: $IMAGE_SMTP
    restart: unless-stopped
    hostname: $DOMAIN
    networks:
      - backend
    environment:
      - SES_USER
      - SES_PASSWORD
      - SES_REGION
  nginx:
    image: $IMAGE_NGINX
    restart: unless-stopped
    command: /docker_cmd.sh
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/wordpress:ro
      - ../nginx/nginx.conf.tpl:/etc/nginx/nginx.conf.tpl:ro
      - ../nginx/docker_cmd.sh:/docker_cmd.sh:ro
      - ../var/letsencrypt:/etc/letsencrypt:ro
      - ../var/uploads:/var/www/uploads:ro
      - ../var/plugins:/var/www/plugins:ro
      - ../var/vhosts:/var/www/vhosts:ro
    environment:
      - DOMAIN
  mysql:
    image: mariadb:10.4
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
      - ../mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  php:
    image: $IMAGE_PHP
    restart: unless-stopped
    command: /usr/local/wpheadless/docker_cmd.sh
    networks:
      - backend
    volumes:
      - wordpress:/var/wordpress:ro
      - ../php:/usr/local/wpheadless:ro
      - ../var/uploads:/var/www/uploads
      - ../var/plugins:/var/www/plugins:ro
      - ../wordpress/themes:/var/www/themes:ro
      - ../wordpress/mu-plugins:/var/www/mu-plugins:ro
networks:
  frontend:
