version: "3"
services:
  x-task-certbot: &task-certbot
    image: $IMAGE_CERTBOT
    entrypoint: []
    working_dir: $PWD
    volumes:
      - ../tasks:${PWD}/tasks:ro
      - ../var/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN
      - ADMIN_EMAIL
  task-lerenew:
    <<: *task-certbot
    volumes:
      - ../tasks:${PWD}/tasks:ro
      - ../var/letsencrypt:/etc/letsencrypt
      - ../var/vhosts:/var/www/vhosts
  task-leissue:
    <<: *task-certbot
    ports:
      - 80:80
      - 443:443
  task-openssl:
    <<: *task-certbot
    command: sh
  task-mysql-proxy:
    image: marcnuri/port-forward
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      - REMOTE_HOST=mysql
      - REMOTE_PORT=3306
      - LOCAL_PORT=3306
  task-wp:
    image: $IMAGE_WORDPRESS
    entrypoint: []
    working_dir: $PWD
    user: root
    networks:
      - backend
    volumes:
      - wordpress:/var/wordpress
      - ..:/$PWD
      - ../var:/var/www
    environment:
      - DOMAIN
      - ADMIN_EMAIL
      - DB_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MAIL_FROM_NAME
      - MAIL_FROM_EMAIL
      - APPROOT=$PWD
      - SMTPHOST=smtp
      - DB_HOST=mysql
      - DB_NAME=wpheadless
      - DB_USER=wpheadless
      - WORDPRESS_VERSION=5.3.2
      - WORDPRESS_TITLE=WpHeadless
      - ACF_PRO_VERSION=5.8.7
      - WORDPRESS_PLUGINS=
          custom-post-type-ui=1.7.3
          acf-to-rest-api=3.1.0
          wordpress-importer=0.6.4
          disable-comments=1.10.2
          title-and-nofollow-for-links=1.09
          wp-security-audit-log=4.0.0
          activity-log-mainwp=1.4.1
